# Generated by Django 2.1.2 on 2019-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('plate_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('black_time', models.DateField()),
                ('vlolation_info', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('plate_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('in_date', models.DateTimeField()),
                ('out_date', models.DateTimeField(null=True)),
                ('stay_date', models.IntegerField(null=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('car_type', models.CharField(max_length=20)),
                ('enter_info', models.CharField(max_length=20)),
                ('exit_info', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='car_school',
            fields=[
                ('plate_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('word_number', models.CharField(max_length=20)),
                ('idcard', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('partment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chage_money',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_type', models.CharField(max_length=20)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charge_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='charge',
            fields=[
                ('plate_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(max_length=20)),
                ('charge_time', models.DateTimeField()),
                ('collector', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='charge_standard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hour_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cross_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('able', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_image', models.BinaryField(null=True)),
                ('exit_image', models.BinaryField(null=True)),
                ('plate_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=200)),
                ('operation_time', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='partment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partment_id', models.IntegerField()),
                ('partment_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='plate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_id', models.IntegerField()),
                ('power_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('job', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('power_id', models.IntegerField()),
            ],
        ),
    ]
